name: StorageBuddy
options:
  bundleIdPrefix: com.alki.storagebuddy
  deploymentTarget:
    macOS: '14.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    MACOSX_DEPLOYMENT_TARGET: '14.0'
    DEVELOPMENT_TEAM: ''
    CODE_SIGN_STYLE: Automatic
    PRODUCT_NAME: StorageBuddy
    GENERATE_INFOPLIST_FILE: YES

schemes:
  StorageBuddy:
    build:
      targets:
        StorageBuddy: all
    run:
      config: Debug

packages: {}

targets:
  StorageBuddy:
    type: application
    platform: macOS
    deploymentTarget: '14.0'
    sources:
      - path: StorageBuddy
    settings:
      config:
        Debug:
          CODE_SIGNING_ALLOWED: NO
          CODE_SIGNING_REQUIRED: NO
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.alki.storagebuddy
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleIconName: AppIcon
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_NSHumanReadableCopyright: 'Copyright (c) 2026 ALKI'
        INFOPLIST_KEY_CFBundleDisplayName: Storage Buddy
